[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[ui]
hideTopBar = true

[global]
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = true
